# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'SDWebImageAnalyse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDWebImageAnalyse
   pod 'SDWebImage', '~> 5.15.5'

end
